/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedJobsRouteImport } from './routes/_authed/jobs'
import { Route as AuthedFinanceRouteImport } from './routes/_authed/finance'
import { Route as ApiAuthIndexRouteImport } from './routes/api/auth/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedJobsRoute = AuthedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFinanceRoute = AuthedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthIndexRoute = ApiAuthIndexRouteImport.update({
  id: '/api/auth/',
  path: '/api/auth/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/finance': typeof AuthedFinanceRoute
  '/jobs': typeof AuthedJobsRoute
  '/api/auth/': typeof ApiAuthIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/finance': typeof AuthedFinanceRoute
  '/jobs': typeof AuthedJobsRoute
  '/': typeof AuthedIndexRoute
  '/api/auth': typeof ApiAuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/finance': typeof AuthedFinanceRoute
  '/_authed/jobs': typeof AuthedJobsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/api/auth/': typeof ApiAuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/finance' | '/jobs' | '/api/auth/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/finance' | '/jobs' | '/' | '/api/auth'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/finance'
    | '/_authed/jobs'
    | '/_authed/'
    | '/api/auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthIndexRoute: typeof ApiAuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/jobs': {
      id: '/_authed/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthedJobsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/finance': {
      id: '/_authed/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthedFinanceRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/': {
      id: '/api/auth/'
      path: '/api/auth'
      fullPath: '/api/auth/'
      preLoaderRoute: typeof ApiAuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedRouteChildren {
  AuthedFinanceRoute: typeof AuthedFinanceRoute
  AuthedJobsRoute: typeof AuthedJobsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedFinanceRoute: AuthedFinanceRoute,
  AuthedJobsRoute: AuthedJobsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthIndexRoute: ApiAuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
